### ISSUE TITLE
json_decode: fails with number int frac

### ISSUE THREAD

**Issue by marcioAlmada** [remicollet/pecl-json-c#12]
Hello, @remicollet.

I just noticed a subtle difference between ext/json and pecl-json-c, involving json_decode function behavior, and thought it might be a bug.

With ext/json extension, int frac numbers `[.][0-9]+` are accepted and following decode is succesfull:

```php
var_dump( json_decode('.1') === 0.1 )
>> true
```

Now the same test with pecl-json-c extension becomes unsuccessful:

```php
var_dump( json_decode('.1') === 0.1 )
>> false
```

The same applies with `JSON_PARSER_NOTSTRICT`:

```php
json_decode('.1', false, 512, JSON_PARSER_NOTSTRICT)
```

Is this a bug? I guess the intended behavior of pecl-json-c is to be compatible with ext/json (keeping backwards compatibility), so maybe it's a good idea to implement this even in case it's not a bug :smile:

Cheers!

**Comment by cmb69** [comment]
@remicollet wrote
> From http://json.org/ => a number must start with a digit.
>
> So, I rather think, this is a bug in ext/json ;)

However, [RFC 4627](https://tools.ietf.org/html/rfc4627) and [RFC 7159](https://tools.ietf.org/html/rfc7159) both state:

> A JSON parser MAY accept non-JSON forms or extensions.

So *accepting* a float without a leading digit would still be standard conformant. :smile:

**Comment by remicollet** [comment]
Fixed to reduce dif with ext/json in 5.x, but in 7.0, ".1" is not accepted anymore.

**Comment by remicollet** [comment]
Please test welcome on master (1.3.8dev)
