### ISSUE TITLE
json_decode: integer overflow detected 1.3.3

### ISSUE THREAD

**Issue by nenad007** [remicollet/pecl-json-c#13]
Hello @remicollet 

With 1.3.3 we got Notice with json_decode: integer overflow detected on the same data set 1.3.2 don't show any (no Warning, no Notice). 

1.3.3

```
var_dump(json_decode('{ "testval": 12345678901234567890}'))

PHP Notice:  json_decode(): integer overflow detected in /tmp/test.php on line 3
object(stdClass)#1 (1) {
  ["testval"]=>
  int(9223372036854775807)
}
```

1.3.2

```
 var_dump(json_decode('{ "testval": 12345678901234567890}'))

object(stdClass)#1 (1) {
  ["testval"]=>
 int(9223372036854775807)
}
```

I'm also confused why I don't get the right value back. 

Is this a bug?

**Comment by ghost** [comment]
Note that this bug only applies to the remicollet pecl extension. The native json extension for php handles the maximum 64 bit integer properly. So you will only stumble on this bug with an installation that depends on the remicollet extension. What a day tracking this down.

Thanks to @scoolen for the 'missing' sort workaround.

**Comment by remicollet** [comment]
> So you will only stumble on this bug with an installation that depends on the remicollet extension. 

No: that depends of an outdated version of the ext.

```
$ php56 -r 'var_dump(phpversion("json"), json_decode("[12".PHP_INT_MAX."]"));'
string(6) "1.3.10"
array(1) {
  [0]=>
  float(1.2922337203685E+20)
}

```
