### ISSUE TITLE
Add functions json_prettify and json_uglify

### ISSUE THREAD

**Issue by marcioAlmada** [remicollet/pecl-json-c#15]
Currently, using `JSON_PRETTY_PRINT` option, we already can uglify and prettify json strings though `json_encode` function but it takes an unnecessary decode step:

```php
$json   = '[{},{}]';
$pretty = json_encode(json_decode($json), JSON_PRETTY_PRINT);
$ugly   = json_encode(json_decode($pretty));
```
I would like to suggest the addition of two new functions: `json_prettify` and `json_uglify`. New user land code would look like this:

```php
$json   = '[{},{}]';
$pretty = json_prettify($json);
$ugly   = json_uglify($pretty);
```
I think json formatting domain is quite related to this extension. Do you think it's a good idea?

**Comment by remicollet** [comment]
No plan to implement
