### ISSUE TITLE
Decoding a random string returns an integer.

### ISSUE THREAD

**Issue by kenguest** [remicollet/pecl-json-c#19]
I have a function that does a json_decode to data it retrieves on the fly - if json_last_error() === JSON_ERROR_NONE it returns what was given back by json_decode.

kguest@radagast:~$ php -v
PHP 5.5.3-1ubuntu2.5 (cli) (built: Jun 25 2014 17:18:20) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2013 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

kguest@radagast:~$ php -a
Interactive mode enabled

php > $a = "7f020e68a7";
php > var_dump(json_decode($a));
int(7)

but the following works as expected:

php > var_dump(json_decode("hello"));
NULL

**Comment by remicollet** [comment]
It seems this one is already fixed.

    $ php -r 'var_dump(json_decode("7f"));'
    NULL
