### ISSUE TITLE
This is more permissive for single quote quoted property names than built-in PHP parser

### ISSUE THREAD

**Issue by jaydiablo** [remicollet/pecl-json-c#23]
This bit of code is processed by the PECL JSON extension just fine:

```
$json = "{
        'foo': \"bar\"
}";

var_dump( json_decode($json) );
```
>php > $json = "{
php "         'foo': \"bar\"
php " }";
php >
php > var_dump( json_decode($json) );
class stdClass#1 (1) {
  public $foo =>
  string(3) "bar"
}

But, run through the built-in PHP decoder it returns NULL: http://3v4l.org/1KRKH

The JSONLint validator (http://jsonlint.com/) also doesn't accept this as valid JSON.

![screen shot 2015-07-02 at 1 48 57 pm](https://cloud.githubusercontent.com/assets/136907/8486339/27b8fd90-20c1-11e5-8c18-2b437e8db98b.png)

This was tested against version 1.3.7 (current as of this writing) of the PECL extension.

>json support => enabled
json version => 1.3.7
json support => yes

**Comment by remicollet** [comment]
Please test welcome on master (1.3.8dev)
