### ISSUE TITLE
is this extension needed in php7 ?

### ISSUE THREAD

**Issue by younes0** [remicollet/pecl-json-c#26]
is this extension needed in php7 ?
if not, we could add this indication in README
thanks

**Comment by remicollet** [comment]
No, this extension will not be available fot PHP 7

PHP 7 have a new free ext/json, so initial issue (non-free ext/json) is fixed.

**Comment by JoyceBabu** [comment]
Does the new `ext/json` support `JSON_PARSER_NOTSTRICT`?

**Comment by remicollet** [comment]
No.
