### ISSUE TITLE
String with IP-address recognized as float by json_decode

### ISSUE THREAD

**Issue by cmb69** [remicollet/pecl-json-c#29]
```
var_dump(json_decode('10.7.11.122'));
```

outputs

```
10.7
```

which is certainly unexpected.

Respective PHP-Info:

```
json support => enabled
json version => 1.3.6
JSON-C headers version => 0.11.99
JSON-C library version => 0.11.99
```

This was originally reported as https://bugs.php.net/72574 which doesn't seem to be the proper place to report json-c issues, as the PECL page says this is the appropriate issue tracker.

**Comment by remicollet** [comment]
You use an outdated version.

```
$ php -r 'var_dump(json_decode("10.7.11.122"));'
NULL

```

**Comment by cmb69** [comment]
Indeed, that has been already fixed with https://github.com/remicollet/pecl-json-c/commit/c24fdc6, as pointed out by Nikita in the PHP bug tracker. It's a Debian issue.
